

# Java de Android Studio
org.gradle.java.home=C\:/PROGRA~1/Android/Android Studio/jbr

# MEMORIA Y RENDIMIENTO 
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

#COMPATIBILIDAD MODERNA
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

#  SOPORTE PARA LIBRERÍAS ANTIGUAS 
android.enableJetifier=true